set(_CATKIN_CURRENT_PACKAGE "projet_rob_mob")
set(projet_rob_mob_VERSION "0.0.0")
set(projet_rob_mob_MAINTAINER "firas <firas@todo.todo>")
set(projet_rob_mob_PACKAGE_FORMAT "2")
set(projet_rob_mob_BUILD_DEPENDS )
set(projet_rob_mob_BUILD_EXPORT_DEPENDS )
set(projet_rob_mob_BUILDTOOL_DEPENDS "catkin")
set(projet_rob_mob_BUILDTOOL_EXPORT_DEPENDS )
set(projet_rob_mob_EXEC_DEPENDS )
set(projet_rob_mob_RUN_DEPENDS )
set(projet_rob_mob_TEST_DEPENDS )
set(projet_rob_mob_DOC_DEPENDS )
set(projet_rob_mob_URL_WEBSITE "")
set(projet_rob_mob_URL_BUGTRACKER "")
set(projet_rob_mob_URL_REPOSITORY "")
set(projet_rob_mob_DEPRECATED "")